import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'

const montserrat = Montserrat({ subsets: ['latin'] })

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} vsc-initialized`}>{children}</body>
    </html>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
